[2024-10-10T17:41:20.361+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-10T17:41:20.460+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_info scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-10T17:41:20.517+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_info scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-10T17:41:20.528+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-10T17:41:20.628+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_save_company_basic_info> on 2024-10-04 00:00:00+00:00
[2024-10-10T17:41:20.659+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1437) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T17:41:20.680+0000] {standard_task_runner.py:72} INFO - Started process 1499 to run task
[2024-10-10T17:41:20.684+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'extract_and_save_company_basic_info', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '4321', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5iw4_brx']
[2024-10-10T17:41:20.715+0000] {standard_task_runner.py:105} INFO - Job 4321: Subtask extract_and_save_company_basic_info
[2024-10-10T17:41:21.587+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_info scheduled__2024-10-04T00:00:00+00:00 [running]> on host 7746de5121f6
[2024-10-10T17:41:22.832+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='extract_and_save_company_basic_info' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-10-10T17:41:22.852+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-10T17:41:22.858+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-10T17:41:22.943+0000] {logging_mixin.py:190} INFO - Current task name:extract_and_save_company_basic_info state:running start_date:2024-10-10 17:41:20.469381+00:00
[2024-10-10T17:41:22.976+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-10-10T17:41:23.011+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-10T17:41:23.187+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-10-10T17:41:52.515+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-10-10T17:41:52.670+0000] {sql.py:509} INFO - Running statement: 
                INSERT INTO company_basic_info (date, authorized_capital, paid_up_capital, type_of_instrument, face_per_value, market_lot,
                                                total_no_outstanding_securities, sector, company_id) 
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);
            , parameters: (datetime.datetime(2024, 10, 10, 17, 41, 49, 961183), 0, '2,899.23', 'Mutual Funds', '10.0', '1', '289,923,349', 'Mutual Funds', 1)
[2024-10-10T17:41:52.836+0000] {job.py:229} INFO - Heartbeat recovered after 26.64 seconds
[2024-10-10T17:41:52.792+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 194, in extract_and_save_company_basic_data
    hook.run(insert_basic_info_query, parameters=(datetime.now(), basic_info_data[0], basic_info_data[2], basic_info_data[3], basic_info_data[4],
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 512, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "company_basic_info_company_id_key"
DETAIL:  Key (company_id)=(1) already exists.

[2024-10-10T17:41:53.172+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-10T17:41:53.174+0000] {logging_mixin.py:190} INFO - Task start:2024-10-10 17:41:20.469381+00:00 end:2024-10-10 17:41:53.171450+00:00 duration:32.702069
[2024-10-10T17:41:53.175+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_and_save_company_basic_info> dag:<DAG: scrape_and_save_share_prices_with_company_data> dagrun:<DagRun scrape_and_save_share_prices_with_company_data @ 2024-10-04 00:00:00+00:00: scheduled__2024-10-04T00:00:00+00:00, state:running, queued_at: 2024-10-10 17:36:05.762199+00:00. externally triggered: False>
[2024-10-10T17:41:53.189+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "company_basic_info_company_id_key"
DETAIL:  Key (company_id)=(1) already exists.
[2024-10-10T17:41:53.190+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_save_share_prices_with_company_data, task_id=extract_and_save_company_basic_info, run_id=scheduled__2024-10-04T00:00:00+00:00, execution_date=20241004T000000, start_date=20241010T174120, end_date=20241010T174153
[2024-10-10T17:41:53.397+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-10T17:41:53.400+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4321 for task extract_and_save_company_basic_info (duplicate key value violates unique constraint "company_basic_info_company_id_key"
DETAIL:  Key (company_id)=(1) already exists.
; 1499)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 194, in extract_and_save_company_basic_data
    hook.run(insert_basic_info_query, parameters=(datetime.now(), basic_info_data[0], basic_info_data[2], basic_info_data[3], basic_info_data[4],
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 512, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "company_basic_info_company_id_key"
DETAIL:  Key (company_id)=(1) already exists.

[2024-10-10T17:41:53.621+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-10T17:41:53.872+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T17:41:53.931+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
