[2024-09-27T19:04:16.171+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T19:04:16.207+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-09-27T19:04:16.230+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-09-27T19:04:16.232+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-27T19:04:16.270+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_save_company_basic_data> on 2024-03-24 00:00:00+00:00
[2024-09-27T19:04:16.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=15717) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T19:04:16.289+0000] {standard_task_runner.py:72} INFO - Started process 15721 to run task
[2024-09-27T19:04:16.295+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'extract_and_save_company_basic_data', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '1942', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphunp8a1k']
[2024-09-27T19:04:16.300+0000] {standard_task_runner.py:105} INFO - Job 1942: Subtask extract_and_save_company_basic_data
[2024-09-27T19:04:16.402+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data scheduled__2024-03-24T00:00:00+00:00 [running]> on host 13b5797a93ab
[2024-09-27T19:04:16.609+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='extract_and_save_company_basic_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-09-27T19:04:16.612+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T19:04:16.613+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T19:04:16.614+0000] {logging_mixin.py:190} INFO - Current task name:extract_and_save_company_basic_data state:running start_date:2024-09-27 19:04:16.208147+00:00
[2024-09-27T19:04:16.615+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T19:04:16.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T19:04:16.634+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T19:04:20.116+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T19:04:20.124+0000] {sql.py:509} INFO - Running statement: 
            INSERT INTO company_basic_info (date, authorized_capital, paid_up_capital, type_of_instrument, face_per_value, market_lot,
                                            total_no_outstanding_securities, sector, company_id) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);
        , parameters: (datetime.datetime(2024, 9, 27, 19, 4, 20, 87081), '', 'Mutual Funds', '10.0', '1', '289,923,349', 'Mutual Funds', 'Closing Price Graph:\n\n-Select Option-\n1 month\n3 months\n6 months\n9 months\n1 year\n2 years\n\nTotal Trade Graph:\n\n-Select Option-\n1 month\n3 months\n6 months\n9 months\n1 year\n2 years\n\nTotal Volume Graph:  \n\n-Select Option-\n1 month\n3 months\n6 months\n9 months\n1 year\n2 years', 1)
[2024-09-27T19:04:20.138+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 165, in extract_and_save_company_basic_data
    hook.run(insert_basic_info_query, parameters=(datetime.now(), basic_info_data[1], basic_info_data[3], basic_info_data[4], basic_info_data[5],
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 512, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedTable: relation "company_basic_info" does not exist
LINE 2:             INSERT INTO company_basic_info (date, authorized...
                                ^

[2024-09-27T19:04:20.220+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-27T19:04:20.247+0000] {logging_mixin.py:190} INFO - Task start:2024-09-27 19:04:16.208147+00:00 end:2024-09-27 19:04:20.219686+00:00 duration:4.011539
[2024-09-27T19:04:20.254+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_and_save_company_basic_data> dag:<DAG: scrape_and_save_share_prices_with_company_data> dagrun:<DagRun scrape_and_save_share_prices_with_company_data @ 2024-03-24 00:00:00+00:00: scheduled__2024-03-24T00:00:00+00:00, state:running, queued_at: 2024-09-27 19:03:14.390763+00:00. externally triggered: False>
[2024-09-27T19:04:20.264+0000] {logging_mixin.py:190} INFO - Failure caused by relation "company_basic_info" does not exist
LINE 2:             INSERT INTO company_basic_info (date, authorized...
                                ^
[2024-09-27T19:04:20.268+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_save_share_prices_with_company_data, task_id=extract_and_save_company_basic_data, run_id=scheduled__2024-03-24T00:00:00+00:00, execution_date=20240324T000000, start_date=20240927T190416, end_date=20240927T190420
[2024-09-27T19:04:20.333+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T19:04:20.347+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1942 for task extract_and_save_company_basic_data (relation "company_basic_info" does not exist
LINE 2:             INSERT INTO company_basic_info (date, authorized...
                                ^
; 15721)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 165, in extract_and_save_company_basic_data
    hook.run(insert_basic_info_query, parameters=(datetime.now(), basic_info_data[1], basic_info_data[3], basic_info_data[4], basic_info_data[5],
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 512, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedTable: relation "company_basic_info" does not exist
LINE 2:             INSERT INTO company_basic_info (date, authorized...
                                ^

[2024-09-27T19:04:20.443+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T19:04:20.576+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T19:04:20.585+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
